In [30]:
import numpy as np


The Basics

In [31]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [32]:
b = np.array([[9.0,5.0,3.0],[2.0, 1.0, 8.0]])
print(b)

# Get Dimension and Shape
b.ndim
b.shape

[[9. 5. 3.]
 [2. 1. 8.]]


(2, 3)

Accessing/Changing Elements in rows, columns etc...

In [33]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r,c]
print(a[1,5])

# Get a specific row
print(a[1, :])

# Get a specific column
print(a[:,2])


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[ 8  9 10 11 12 13 14]
[ 3 10]


In [34]:
# More advanced [start:end:step]
print(a[0,1:6:2])

# Replace Elements
a[1,5] = 20
print(a)
# Replace row/column
a[:,2] = [1,8]
print(a)


[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  8 11 12 20 14]]


3-D Example

In [35]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get element (work outside in)
b[0,1,1]

b[:,1,:]

array([[3, 4],
       [7, 8]])

Initializing Difffertent Types of Arrays

In [37]:
# All 0's Matrix
np.zeros((2,3,3))

#All 1's MAtrix
np.ones((2,3))

# Any other Number
np.full((2,2),99)


array([[99, 99],
       [99, 99]])

In [38]:
#Matrix with Random Decimal Numbers
np.random.rand(4,2)

array([[0.57619675, 0.7493636 ],
       [0.34681425, 0.92950865],
       [0.4576399 , 0.40169439],
       [0.88634498, 0.61405839]])

In [39]:
#Matrix with Random Numbers
np.random.randint(7, size=(3,3))

array([[4, 0, 5],
       [0, 6, 4],
       [6, 5, 4]])

In [40]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#Creating Specific Matrix
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

output = np.ones((5,5))
#print(output)

middle = np.zeros((3,3))
#print(middle)

middle[1,1]  = 9
#print(middle)

output[1:4,1:4] = middle
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics

In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a + 2

array([3, 4, 5, 6])

In [49]:
a ** 2

array([ 1,  4,  9, 16])

In [50]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Alegra

In [62]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

#Matrix Multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [56]:
#FInding Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [61]:
stats = np.array([[1,2,3],[4,5,6]])
stats

np.min(stats)
np.max(stats)
np.sum(stats)


6