In [1]:
import numpy as np


The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,5.0,3.0],[2.0, 1.0, 8.0]])
print(b)

# Get Dimension and Shape
b.ndim
b.shape

[[9. 5. 3.]
 [2. 1. 8.]]


(2, 3)

Accessing/Changing Elements in rows, columns etc...

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r,c]
print(a[1,5])

# Get a specific row
print(a[1, :])

# Get a specific column
print(a[:,2])


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[ 8  9 10 11 12 13 14]
[ 3 10]


In [16]:
# More advanced [start:end:step]
print(a[0,1:6:2])

# Replace Elements
a[1,5] = 20
print(a)
# Replace row/column
a[:,2] = [1,8]
print(a)


[2 4 6]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  8 11 12 20 14]]


3-D Example

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# Get element (work outside in)
b[0,1,1]

b[:,1,:]

array([[3, 4],
       [7, 8]])

Initializing Difffertent Types of Arrays

In [26]:
# All 0's Matrix
np.zeros((2,3,3))

#All 1's MAtrix
np.ones((2,3))

# Any other Number
np.full((2,2),99)


array([[99, 99],
       [99, 99]])