In [2]:
import numpy as np


The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,5.0,3.0],[2.0, 1.0, 8.0]])
print(b)

# Get Dimension and Shape
b.ndim
b.shape

[[9. 5. 3.]
 [2. 1. 8.]]


(2, 3)

Accessing/Changing Elements in rows, columns etc...

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r,c]
print(a[1,5])

# Get a specific row
print(a[1, :])

# Get a specific column
print(a[:,2])


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[ 8  9 10 11 12 13 14]
[ 3 10]


In [6]:
# More advanced [start:end:step]
print(a[0,1:6:2])

# Replace Elements
a[1,5] = 20
print(a)
# Replace row/column
a[:,2] = [1,8]
print(a)


[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  8 11 12 20 14]]


3-D Example

In [7]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
# Get element (work outside in)
b[0,1,1]

b[:,1,:]

array([[3, 4],
       [7, 8]])

Initializing Difffertent Types of Arrays

In [9]:
# All 0's Matrix
np.zeros((2,3,3))

#All 1's MAtrix
np.ones((2,3))

# Any other Number
np.full((2,2),99)


array([[99, 99],
       [99, 99]])

In [10]:
#Matrix with Random Decimal Numbers
np.random.rand(4,2)

array([[0.93426675, 0.8814056 ],
       [0.14997906, 0.1049529 ],
       [0.66361301, 0.29504866],
       [0.7292781 , 0.14585028]])

In [11]:
#Matrix with Random Numbers
np.random.randint(7, size=(3,3))

array([[3, 6, 1],
       [6, 4, 5],
       [4, 0, 2]])

In [12]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#Creating Specific Matrix
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

output = np.ones((5,5))
#print(output)

middle = np.zeros((3,3))
#print(middle)

middle[1,1]  = 9
#print(middle)

output[1:4,1:4] = middle
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics

In [14]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a + 2

array([3, 4, 5, 6])

In [16]:
a ** 2

array([ 1,  4,  9, 16])

In [17]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Alegra

In [18]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

#Matrix Multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [19]:
#FInding Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [20]:
stats = np.array([[1,2,3],[4,5,6]])
stats

np.min(stats)
np.max(stats)
np.sum(stats)


21

Advanced Indexing using Numpy

#Creating Specific Matrix
# 1  2  3  4  5
# 6  7  8  9  10
# 11 12 13 14 15
# 16 17 18 19 20
# 21 22 23 24 25
# 26 27 28 29 30

In [57]:

outline = np.arange(1,31)
main = outline.reshape(6,5)

main[2:4,0:2]
main[[0,1,2,3], [1,2,3,4]]
main[[0,4,5],3:5]


array([[ 4,  5],
       [24, 25],
       [29, 30]])